FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y install cron curl
WORKDIR /crontab
COPY api-cron /etc/cron.d/api-cron
RUN chmod 0644 /etc/cron.d/api-cron
RUN touch /var/log/cron.log
# Give execution rights on the cron job
RUN chmod +x /etc/cron.d/api-cron
# Create the log file to be able to run tail
RUN touch /var/log/cron.log
CMD cron && tail -f /var/log/cron.log
