# Use continuumio/miniconda3 as a base image 
FROM continuumio/miniconda3

# Set /HW3-Assigned as a working directory
WORKDIR /HW3-Assigned

# Copy environment.yml
COPY * .

# create an environment using environment.yml
RUN conda env create -n msds692_hw -f environment.yml

# expose port 8501
EXPOSE 8501

# run the main.py as streamlit server.
CMD ["conda", "run", "--no-capture-output", "-n", "msds692_hw", "streamlit", "run", "main.py", "--server.address", "0.0.0.0"]
