# Use continuumio/miniconda3 as a base image 
FROM continuumio/miniconda3

# Set /HW3-Assigned as a working directory
WORKDIR /HW3-Assigned

# Copy environment.yml
COPY * .

# create an environment using environment.yml
RUN conda env create -n msds692_hw -f environment.yml

# install fastapi[standard] for fastapi's cli on the environment
RUN conda install -n msds692_hw fastapi[standard] 

# expose port 8000
EXPOSE 8000

# run the extract_save_data.py as fastapi server.
CMD ["conda", "run", "--no-capture-output", "-n", "msds692_hw", "fastapi", "run", "extract_save_data.py", "--port=8000", "--host=0.0.0.0"]
